language: ruby
sudo: false
git:
  depth: false
cache: bundler
before_install:
 - wget https://raw.githubusercontent.com/progit/progit2-pub/master/bootstrap.sh
 - sh bootstrap.sh
script:
  - bundle exec rake book:build
  - mkdir public
  - cp progit.html public/index.html
  - cp progit.{pdf,epub} public/
  - cp -r images/ public/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  local_dir: ./public
  on:
    branch: develop
addons:
  apt:
    packages:
      - epubcheck
notifications:
  email:
    on_success: never
    on_failure: always
